config/routes.rb
class AdminRequest
  def self.matches?(request)
    !invalid_admin_host?(request.host)
  end

  def self.invalid_admin_host?(host)
    Rails.env.production? && Whitehall.admin_host != host
  end
end

Whitehall::Application.routes.draw do
  def redirect(path, options = {prefix: Whitehall.router_prefix})
    super(options[:prefix] + path)
  end

  def external_redirect(path_prefix, target)
    get path_prefix => redirect(target, prefix: '')
    get "#{path_prefix}/*anything" => redirect(target, prefix: '')
  end

  root to: redirect("/admin/"), constraints: lambda { |request|
    ::Whitehall.admin_host == request.host
  }

  get '/government/ministers/minister-of-state--11' => redirect('/government/people/kris-hopkins', prefix: '')

  get '/browse/*parent_tag/:id', to: 'mainstream_categories#show'

  namespace 'api' do
    resources :detailed_guides, path: 'specialist', only: [:show, :index], defaults: { format: :json } do
      collection do
        get :tags
      end
    end
    resources :organisations, only: [:index, :show], defaults: { format: :json }
    resources :world_locations, path: 'world-locations', only: [:index, :show], defaults: { format: :json } do
      resources :worldwide_organisations, path: 'organisations', only: [:index], defaults: { format: :json }
    end
    resources :worldwide_organisations, path: 'worldwide-organisations', only: [:show], defaults: { format: :json }
  end

  scope Whitehall.router_prefix, shallow_path: Whitehall.router_prefix do
    external_redirect '/organisations/ministry-of-defence-police-and-guarding-agency',
      "http://webarchive.nationalarchives.gov.uk/20121212174735/http://www.mod.uk/DefenceInternet/AboutDefence/WhatWeDo/SecurityandIntelligence/MDPGA/"

    root to: redirect("/", { prefix: '' }), via: :get, as: :main_root
    get "/how-government-works" => "home#how_government_works", as: 'how_government_works'
    scope '/get-involved' do
      root to: 'home#get_involved', as: :get_involved, via: :get
      get 'take-part' => redirect('/get-involved#take-part')
      get 'take-part/:id', to: 'take_part_pages#show', as: 'take_part_page'
    end

    # Past foreign secretaries are currently hard-coded, so this
    # resource falls straight through to views.
    resources :past_foreign_secretaries, path: "/history/past-foreign-secretaries", only: [:index, :show]
    # Past chancellors is also hard-coded
    get "history/past-chancellors" => 'historic_appointments#past_chancellors'

    # Past foreign secretaries and past chancellors are here for the
    # purposes of reversing URLs in a consistent way from other views.

    # TODO: make these dynamic, they're hard-coded above.
    get "/history/:role" => "historic_appointments#index", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: 'historic_appointments'
    get "/history/:role/:person_id" => "historic_appointments#show", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: 'historic_appointment'
    resources :histories, path: "history", only: [:index, :show]

    resource :email_signups, path: 'email-signup', only: [:create, :new]
    get "/email-signup", to: redirect('/')

    get '/feed' => 'home#feed', defaults: { format: :atom }, constraints: { format: :atom }, as: :atom_feed
    get '/tour' => redirect("/tour", prefix: "")

    resources :announcements, only: [:index], path: 'announcements', localised: true
    resources :policies, only: [:index, :show], localised: true do
      member do
        get :activity
      end
      resources :supporting_pages, path: "supporting-pages", only: [:index, :show]
    end
    resources :news_articles, path: 'news', only: [:show], localised: true
    resources :fatality_notices, path: 'fatalities', only: [:show]
    get "/news" => redirect("/announcements"), as: 'news_articles'
    get "/fatalities" => redirect("/announcements"), as: 'fatality_notices'

    get "/latest" => 'latest#index', as: 'latest'

    resources :publications, only: [:index, :show], localised: true
    get "/publications/:publication_id/:id" => 'html_attachments#show', as: 'publication_html_attachment'

    resources :case_studies, path: 'case-studies', only: [:show, :index], localised: true
    resources :speeches, only: [:show], localised: true
    resources :statistical_data_sets, path: 'statistical-data-sets', only: [:index, :show]
    get "/speeches" => redirect("/announcements")
    resources :statistics_announcements, path: 'statistics/announcements', only: [:index, :show]
    resources :statistics, only: [:index, :show], localised: true
    resources :world_location_news_articles, path: 'world-location-news', only: [:index, :show], localised: true

    resources :worldwide_priorities, path: "priority", only: [:index, :show], localised: true do
      member do
        get :activity
      end
    end

    resources :consultations, only: [:index, :show] do
      collection do
        get :open
        get :closed
        get :upcoming
      end
    end
    get "/consultations/:consultation_id/:id" => 'html_attachments#show', as: 'consultation_html_attachment'

    resources :topics, path: "topics", only: [:index, :show]
    resources :topical_events, path: "topical-events", only: [:index, :show] do
      resource :about_pages, path: "about", only: [:show]
    end

    resources :document_collections, only: [:show], path: 'collections'
    get '/collections' => redirect("/publications")
    resources :organisations, only: [:index], localised: false
    resources :organisations, only: [:show], localised: true do
      get '/series/:slug' => redirect("/collections/%{slug}")
      get '/series' => redirect("/publications")

      member do
        get :consultations
        get :chiefs_of_staff, path: 'chiefs-of-staff'
      end
      resources :corporate_information_pages, only: [:show, :index], path: 'about', localised: true
      resources :groups, only: [:show]
    end
    get "/organisations/:organisation_id/groups" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/services-information" => 'services_and_information#show',
      as: :services_and_information
    get "/organisations/:organisation_slug/email-signup" => 'email_signup_information#show',
      as: :organisation_email_signup_information

    resources :ministerial_roles, path: 'ministers', only: [:index, :show], localised: true
    resources :people, only: [:index, :show], localised: true

    resources :policy_groups, path: 'groups', only: [:index, :show]
    resources :operational_fields, path: 'fields-of-operation', only: [:index, :show]
    resources :worldwide_organisations, path: 'world/organisations', only: [:show, :index], localised: true do
      resources :corporate_information_pages, only: [:show], path: 'about', localised: true
      resources :worldwide_offices, path: 'office', only: [:show]
    end

    resources :embassies, path: 'world/embassies', only: [:index]

    resources :world_locations, path: 'world', only: [:index, :show], localised: true
    get 'world/organisations/:organisation_id/office' => redirect('/world/organisations/%{organisation_id}')
    get 'world/organisations/:organisation_id/about' => redirect('/world/organisations/%{organisation_id}')

    constraints(AdminRequest) do
      namespace :admin do
        root to: 'dashboard#index', via: :get

        namespace :api do
          post 'reindex-specialist-sector-editions/*slug', to: 'search#reindex_specialist_sector_editions', as: 'reindex_specialist_sector_editions'
        end

        get 'find-in-admin-bookmarklet' => 'find_in_admin_bookmarklet#index', as: :find_in_admin_bookmarklet_instructions_index
        get 'find-in-admin-bookmarklet/:browser' => 'find_in_admin_bookmarklet#show', as: :find_in_admin_bookmarklet_instructions

        resources :users, only: [:index, :show, :edit, :update]

        resources :authors, only: [:show]
        resource :document_searches, only: [:show]
        resources :document_collections, path: "collections", except: [:index] do
          resources :document_collection_groups, as: :groups, path: 'groups' do
            member { get :delete }
            resource :document_collection_group_membership, as: :members,
                                                        path: 'members',
                                                        only: [:destroy]
          end
          resource :document_collection_group_membership, as: :new_member,
                                                      path: 'members',
                                                      only: [:create]
          post 'groups/update_memberships' => 'document_collection_groups#update_memberships', as: :update_group_memberships
        end
        resources :organisations do
          resources :groups, except: [:show]
          resources :corporate_information_pages do
            resources :translations, controller: 'corporate_information_pages_translations'
          end
          resources :contacts do
            resources :translations, controller: 'contact_translations', only: [:create, :edit, :update, :destroy]
            member do
              post :remove_from_home_page
              post :add_to_home_page
            end
            post :reorder_for_home_page, on: :collection
          end
          resources :social_media_accounts
          resources :translations, controller: 'organisation_translations'
          resources :promotional_features do
            resources :promotional_feature_items, as: :items, path: 'items', except: [:index]
          end
          member do
            get :features, localised: true
            get :people
          end
          resource :featured_topics_and_policies_list, path: 'featured-topics-and-policies', only: [:show, :update]
          resources :financial_reports, except: [:show]
          resources :offsite_links
        end

app/models/ministerial_role.rb
class MinisterialRole < Role
  include Searchable

  has_many :edition_ministerial_roles
  has_many :editions, through: :edition_ministerial_roles
  has_many :speeches, through: :role_appointments
  has_many :policies, through: :edition_ministerial_roles, source: :edition, conditions: { "editions.type" => Policy }
  has_many :news_articles, through: :role_appointments, conditions: { "editions.type" => NewsArticle }, uniq: true

  def published_policies(options = {})
    policies
      .latest_published_edition
      .in_reverse_chronological_order
      .limit(options[:limit])
  end

  def published_speeches(options = {})
    speeches
      .latest_published_edition
      .in_reverse_chronological_order
      .limit(options[:limit])
  end

  def published_news_articles(options = {})
    news_articles
      .latest_published_edition
      .in_reverse_chronological_order
      .limit(options[:limit])
  end

  searchable title: :search_title,
             link: :search_link,
             content: :current_person_biography,
             format: 'minister'

  def self.cabinet
    where(cabinet_member: true).alphabetical_by_person
  end

  def ministerial?
    true
  end

  def search_title
    current_person ? "#{current_person.name} (#{to_s})" : to_s
  end

  def destroyable?
    super && editions.empty?
  end

  def search_link
    # This should be ministerial_role_path(self), but we can't use that because friendly_id's #to_param returns
    # the old value of the slug (e.g. nil for a new record) if the record is dirty, and apparently the record
    # is still marked as dirty during after_save callbacks.
    Whitehall.url_maker.ministerial_role_path(slug)
  end

private
  def default_person_name
    name
  end
end

app/controllers/ministerial_roles_controller.rb
class MinisterialRolesController < PublicFacingController
  enable_request_formats show: [:atom]

  def index
    sorter = MinisterSorter.new
    @cabinet_ministerial_roles = decorated_people_and_their_roles(sorter.cabinet_ministers)
    reshuffle_setting = load_reshuffle_setting
    if reshuffle_setting
      @is_during_reshuffle = reshuffle_setting.on
      @reshuffle_messaging = reshuffle_setting.govspeak
    end

    cabinet_roles = MinisterSorter.new(Role.with_translations.includes(:current_people)).also_attends_cabinet
    @also_attends_cabinet = decorated_people_and_their_roles(cabinet_roles)
    @ministers_by_organisation = ministers_by_organisation
    @whips_by_organisation = whips_by_organisation
  end

  def show
    @ministerial_role = RolePresenter.new(MinisterialRole.find(params[:id]), view_context)
    @policies = decorate_collection(@ministerial_role.policies.published.in_reverse_chronological_order, PolicyPresenter)
    set_slimmer_organisations_header(@ministerial_role.organisations)
    set_slimmer_page_owner_header(@ministerial_role.organisations.first)
  end

private
  def decorated_people_and_their_roles(people_and_roles)
    people_and_roles.map do |person, roles|
      [
        PersonPresenter.new(person, view_context),
        roles.map { |r| RolePresenter.new(r, view_context) }
      ]
    end
  end

  def ministers_by_organisation
    Organisation.ministerial_departments.
                 with_translations.
                 with_translations_for(:ministerial_roles).
                 includes(ministerial_roles: [:current_people]).
                 order('organisation_roles.ordering').map do |organisation|
      roles_presenter = RolesPresenter.new(organisation.ministerial_roles, view_context)
      roles_presenter.remove_unfilled_roles!
      [organisation, roles_presenter]
    end
  end

  def whips_by_organisation
    Role.with_translations.includes(:current_people).whip.group_by(&:whip_organisation_id).map do |whip_organisation_id, roles|
      roles_presenter = RolesPresenter.new(roles.sort_by(&:whip_ordering), view_context)
      roles_presenter.remove_unfilled_roles!
      [Whitehall::WhipOrganisation.find_by_id(whip_organisation_id), roles_presenter]
    end.sort_by { |org, whips| org.sort_order }
  end
end

app/helpers/ministerial_roles_helper.rb
module MinisterialRolesHelper
  def ministerial_role_organisation_class(ministerial_role)
    if ministerial_role.organisations.size == 1
      ministerial_role.organisations.first.slug
    else
      'multiple_organisations'
    end
  end

  def array_of_links_to_ministers(ministers)
    ministers.map do |minister|
      link_to minister.current_person_name, minister, class: 'minister-link'
    end
  end

end

app/views/ministerial_roles/_list.html.erb
<%= render_list_of_ministerial_roles(ministerial_roles) do |ministerial_role| %>
  <%= ministerial_role.link %>
<% end %>

app/views/ministerial_roles/_policies.html.erb
<ol class="document-list">
  <% role.published_policies.each do |policy| %>
    <%= content_tag_for :li, policy, class: "document-row" do %>
      <h3><%= policy.link %></h3>
      <ul class="attributes">
        <li class="date"><%= policy.display_date_microformat %></li>
      </ul>
    <% end %>
  <% end %>
</ol>
<div class="read-more">
  <%= link_to t('policies.view_all'), :policies %>
</div>

app/views/ministerial_roles/index.html.erb
<% page_title "Ministers" %>
<% page_class "ministers-index" %>

<header class="block headings-block">
  <div class="inner-block floated-children">
    <%= render partial: 'shared/heading',
              locals: { big: true,
                        heading: "Ministers" } %>

    <p class="intro-paragraph">Read biographies and responsibilities of <a href="#cabinet-ministers">Cabinet ministers</a> and all <a href="#ministers-by-department">ministers by department</a>, as well as the <a href="#whips">whips</a> who help co-ordinate parliamentary business.</p>
  </div>
</header>

<% if @is_during_reshuffle %>
  <div class="block">
    <div class="inner-block">
      <aside class="status-block">
        <%= govspeak_to_html @reshuffle_messaging %>
      </aside>
    </div>
  </div>
<% end %>

<div class="block-2">
  <div class="inner-block floated-children">
    <section class="cab_ministers">
      <h2 class="label" id="cabinet-ministers">Cabinet ministers</h2>
      <ul id="cabinet" class="cabinet-list">
        <% @cabinet_ministerial_roles.each_with_index do |(person, roles), i| %>
          <%= render partial: "people/person",
              locals: {
                person: person,
                roles: roles,
                hlevel: "h3",
                hide_image: false,
                extra_class: (i % 4 == 0) ? 'clear-person' : ''
          } %>
        <% end %>
      </ul>
    </section>
  </div>
</div>
<% if @also_attends_cabinet.any? %>
  <div class="block-2">
    <div class="inner-block floated-children">
      <section class="cab_ministers">
        <h2 class="label" id="also-attends-cabinet-ministers">Also attends Cabinet</h2>
        <ul id="also-attends-cabinet" class="cabinet-list">
          <% @also_attends_cabinet.each_with_index do |(person, roles), i| %>
            <%= render partial: "people/person",
                locals: {
                  person: person,
                  roles: roles,
                  hlevel: "h3",
                  hide_image: false,
                  extra_class: (i % 4 == 0) ? 'clear-person' : '',
                  display_cabinet_attendance: true
            } %>
          <% end %>
        </ul>
      </section>
    </div>
  </div>
<% end %>

<div class="ministers-by-organisation">
  <div class="inner-block floated-children">
    <h2 id="ministers-by-department">Ministers by department</h2>
    <% @ministers_by_organisation.each do |organisation, ministers| %>
      <%= content_tag_for :section, organisation do %>
        <div class="heading">
          <h3>
            <%= link_to organisation_path(organisation), class: logo_classes(organisation: organisation,  size: 'medium', stacked: true) do %>
              <span><%= format_with_html_line_breaks(organisation.logo_formatted_name) %></span>
            <% end %>
          </h3>
        </div>
        <ul class="minister-list">
          <% ministers.with_unique_people.each.with_index do |role, i| %>
            <%= render partial: "people/person",
                locals: {
                  person: PersonPresenter.new(role.current_person, self),
                  roles: ministers.roles_for(role.current_person),
                  hlevel: "h4",
                  prefix: 'by-organisation',
                  hide_image: true,
                  extra_class: (i % 3 == 0) ? 'clear-person' : ''
                } %>
          <% end %>
        </ul>
      <% end %>
      <hr class="keyline">
    <% end %>
  </div>
</div>

<div class="ministers-by-organisation whips">
  <div class="inner-block floated-children">
    <h2 id="whips">Whips</h2>

    <% @whips_by_organisation.each do |whip_organisation, whips| %>
      <%= content_tag_for :section, whip_organisation do %>
        <div class="heading">
          <h3><%= whip_organisation.name %></h3>
        </div>
        <ul class="minister-list">
          <% whips.unique_people.each.with_index do |person, i| %>
            <%= render partial: "people/person",
                locals: {
                  person: PersonPresenter.new(person, self),
                  roles: whips.roles_for(person),
                  hlevel: "h4",
                  prefix: 'by-organisation',
                  hide_image: true,
                  extra_class: (i % 3 == 0) ? 'clear-person' : ''
                } %>
          <% end %>
        </ul>
      <% end %>
      <hr class="keyline">
    <% end %>
  </div>
</div>

app/views/ministerial_roles/show.html.erb
<% page_title @ministerial_role.name %>
<% page_class "ministerial-role-show biographical-page" %>

<%= content_tag_for :div, @ministerial_role, class: 'two-column-page ministerial-department ' + ministerial_role_organisation_class(@ministerial_role) do %>
  <header class="block headings-block">
    <div class="inner-block floated-children">
      <%= render partial: 'shared/heading',
                locals: { type: t('roles.ministerial'),
                        heading: @ministerial_role.name,
                        big: true, extra: true} %>

      <div class="heading-extra">
        <div class="inner-heading">
          <%= render partial: 'shared/available_languages', locals: {object: @ministerial_role } %>
        </div>
      </div>

      <aside class="meta metadata-list">
        <div class="inner-heading">
          <dl>
            <dt><%= t('document.headings.organisations', count: @ministerial_role.organisations.count) %>:</dt>
            <dd>
              <%= render  partial: 'organisations/organisations_name_list',
                          locals: { organisations: @ministerial_role.organisations } %>
            </dd>
            <% if @ministerial_role.occupied? %>
              <dt><%= t('roles.headings.current_holder') %>:</dt>
              <dd><%= link_to @ministerial_role.current_person.name, @ministerial_role.current_person %></dd>
            <% end %>
          </dl>
        </div>
      </aside>
    </div>
  </header>

  <div class="block-2 ">
    <div class="inner-block js-stick-at-top-when-scrolling">
      <section class="contextual-info in-page-navigation ">
        <h1><%= t('document.contents') %></h1>
        <nav role="navigation">
          <ul>
            <li><%= link_to t('roles.headings.responsibilities'), '#responsibilities' %></li>
            <% if @ministerial_role.occupied? %>
              <li><%= link_to t('roles.headings.current_holder'), "#current-role-holder" %></li>
            <% end %>
            <% if @ministerial_role.published_policies.any? %>
              <li><%= link_to t('policies.heading'), "#policies" %></li>
            <% end %>
            <% if @ministerial_role.previous_appointments.any? %>
              <li><%= link_to t('roles.headings.previous_holders'), "#previous-holders-of-this-role" %></li>
            <% end %>
            <% if @ministerial_role.announcements.any? %>
              <li><%= link_to t('announcements.heading'), "#announcements" %></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </div>
  </div>

  <div class="block-3">
    <div class="inner-block" id="responsibilities">
      <%= content_tag_for :section, @ministerial_role, class: "responsibilities" do %>
        <h1><%= t('roles.headings.responsibilities') %></h1>
        <%= @ministerial_role.responsibilities %>
      <% end %>

      <% if @ministerial_role.occupied? %>
        <section class="current-role-holder" id="current-role-holder">
          <h1><%= t('roles.headings.current_holder') %>: <span class="name"><%= @ministerial_role.current_person.name %></span></h1>
          <%= @ministerial_role.current_person.biography %>
          <div class="read-more">
            <%= link_to t('people.read_more'), @ministerial_role.current_person %>
          </div>
        </section>
      <% end %>

      <% if @ministerial_role.supports_historical_accounts? || @ministerial_role.previous_appointments.any? %>
        <section class="previous-roles" id="previous-holders-of-this-role">
          <h1><%= t('roles.previous_holders') %></h1>
          <% if @ministerial_role.supports_historical_accounts? %>
            <p>Find out more about previous holders of this role in our <%= link_to "past #{@ministerial_role.name.pluralize}", historic_appointments_path(@ministerial_role.historic_param) %> section.</p>
          <% elsif @ministerial_role.previous_appointments.any? %>
            <ol class="document-list">
              <% @ministerial_role.previous_appointments.each do |appointment| %>
                <%= content_tag_for :li, appointment, class: "document-row" do %>
                  <h3><%= appointment.person_link %></h3>
                  <ul class="attributes">
                    <li class="date"><%= appointment.date_range %></li>
                  </ul>
                <% end %>
              <% end %>
            </ol>
          <% end %>
        </section>
      <% end %>

      <% if @ministerial_role.published_policies.any? %>
        <section class="policy" id="policies">
          <h1><%= t('policies.heading') %></h1>

          <%= render 'ministerial_roles/policies', role: @ministerial_role %>

        </section>
      <% end %>

      <%= render 'shared/announcement_list', announcer: @ministerial_role %>
    </div>
  </div>
<% end %>