config/routes.rb
class AdminRequest
  def self.matches?(request)
    !invalid_admin_host?(request.host)
  end

  def self.invalid_admin_host?(host)
    Rails.env.production? && Whitehall.admin_host != host
  end
end

Whitehall::Application.routes.draw do
  def redirect(path, options = {prefix: Whitehall.router_prefix})
    super(options[:prefix] + path)
  end

  def external_redirect(path_prefix, target)
    get path_prefix => redirect(target, prefix: '')
    get "#{path_prefix}/*anything" => redirect(target, prefix: '')
  end

  root to: redirect("/admin/"), constraints: lambda { |request|
    ::Whitehall.admin_host == request.host
  }

  get '/government/ministers/minister-of-state--11' => redirect('/government/people/kris-hopkins', prefix: '')

  get '/browse/*parent_tag/:id', to: 'mainstream_categories#show'

  namespace 'api' do
    resources :detailed_guides, path: 'specialist', only: [:show, :index], defaults: { format: :json } do
      collection do
        get :tags
      end
    end
    resources :organisations, only: [:index, :show], defaults: { format: :json }
    resources :world_locations, path: 'world-locations', only: [:index, :show], defaults: { format: :json } do
      resources :worldwide_organisations, path: 'organisations', only: [:index], defaults: { format: :json }
    end
    resources :worldwide_organisations, path: 'worldwide-organisations', only: [:show], defaults: { format: :json }
  end

  scope Whitehall.router_prefix, shallow_path: Whitehall.router_prefix do
    external_redirect '/organisations/ministry-of-defence-police-and-guarding-agency',
      "http://webarchive.nationalarchives.gov.uk/20121212174735/http://www.mod.uk/DefenceInternet/AboutDefence/WhatWeDo/SecurityandIntelligence/MDPGA/"

    root to: redirect("/", { prefix: '' }), via: :get, as: :main_root
    get "/how-government-works" => "home#how_government_works", as: 'how_government_works'
    scope '/get-involved' do
      root to: 'home#get_involved', as: :get_involved, via: :get
      get 'take-part' => redirect('/get-involved#take-part')
      get 'take-part/:id', to: 'take_part_pages#show', as: 'take_part_page'
    end

    # Past foreign secretaries are currently hard-coded, so this
    # resource falls straight through to views.
    resources :past_foreign_secretaries, path: "/history/past-foreign-secretaries", only: [:index, :show]
    # Past chancellors is also hard-coded
    get "history/past-chancellors" => 'historic_appointments#past_chancellors'

    # Past foreign secretaries and past chancellors are here for the
    # purposes of reversing URLs in a consistent way from other views.

    # TODO: make these dynamic, they're hard-coded above.
    get "/history/:role" => "historic_appointments#index", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: 'historic_appointments'
    get "/history/:role/:person_id" => "historic_appointments#show", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: 'historic_appointment'
    resources :histories, path: "history", only: [:index, :show]

    resource :email_signups, path: 'email-signup', only: [:create, :new]
    get "/email-signup", to: redirect('/')

    get '/feed' => 'home#feed', defaults: { format: :atom }, constraints: { format: :atom }, as: :atom_feed
    get '/tour' => redirect("/tour", prefix: "")

    resources :announcements, only: [:index], path: 'announcements', localised: true
    resources :policies, only: [:index, :show], localised: true do
      member do
        get :activity
      end
      resources :supporting_pages, path: "supporting-pages", only: [:index, :show]
    end
    resources :news_articles, path: 'news', only: [:show], localised: true
    resources :fatality_notices, path: 'fatalities', only: [:show]
    get "/news" => redirect("/announcements"), as: 'news_articles'
    get "/fatalities" => redirect("/announcements"), as: 'fatality_notices'

    get "/latest" => 'latest#index', as: 'latest'

    resources :publications, only: [:index, :show], localised: true
    get "/publications/:publication_id/:id" => 'html_attachments#show', as: 'publication_html_attachment'

    resources :case_studies, path: 'case-studies', only: [:show, :index], localised: true
    resources :speeches, only: [:show], localised: true
    resources :statistical_data_sets, path: 'statistical-data-sets', only: [:index, :show]
    get "/speeches" => redirect("/announcements")
    resources :statistics_announcements, path: 'statistics/announcements', only: [:index, :show]
    resources :statistics, only: [:index, :show], localised: true
    resources :world_location_news_articles, path: 'world-location-news', only: [:index, :show], localised: true

    resources :worldwide_priorities, path: "priority", only: [:index, :show], localised: true do
      member do
        get :activity
      end
    end

    resources :consultations, only: [:index, :show] do
      collection do
        get :open
        get :closed
        get :upcoming
      end
    end
    get "/consultations/:consultation_id/:id" => 'html_attachments#show', as: 'consultation_html_attachment'

    resources :topics, path: "topics", only: [:index, :show]
    resources :topical_events, path: "topical-events", only: [:index, :show] do
      resource :about_pages, path: "about", only: [:show]
    end

    resources :document_collections, only: [:show], path: 'collections'
    get '/collections' => redirect("/publications")
    resources :organisations, only: [:index], localised: false
    resources :organisations, only: [:show], localised: true do
      get '/series/:slug' => redirect("/collections/%{slug}")
      get '/series' => redirect("/publications")

      member do
        get :consultations
        get :chiefs_of_staff, path: 'chiefs-of-staff'
      end
      resources :corporate_information_pages, only: [:show, :index], path: 'about', localised: true
      resources :groups, only: [:show]
    end
    get "/organisations/:organisation_id/groups" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/services-information" => 'services_and_information#show',
      as: :services_and_information
    get "/organisations/:organisation_slug/email-signup" => 'email_signup_information#show',
      as: :organisation_email_signup_information

    resources :ministerial_roles, path: 'ministers', only: [:index, :show], localised: true
    resources :people, only: [:index, :show], localised: true

    resources :policy_groups, path: 'groups', only: [:index, :show]
    resources :operational_fields, path: 'fields-of-operation', only: [:index, :show]
    resources :worldwide_organisations, path: 'world/organisations', only: [:show, :index], localised: true do
      resources :corporate_information_pages, only: [:show], path: 'about', localised: true
      resources :worldwide_offices, path: 'office', only: [:show]
    end

    resources :embassies, path: 'world/embassies', only: [:index]

    resources :world_locations, path: 'world', only: [:index, :show], localised: true
    get 'world/organisations/:organisation_id/office' => redirect('/world/organisations/%{organisation_id}')
    get 'world/organisations/:organisation_id/about' => redirect('/world/organisations/%{organisation_id}')

    constraints(AdminRequest) do
      namespace :admin do
        root to: 'dashboard#index', via: :get

        namespace :api do
          post 'reindex-specialist-sector-editions/*slug', to: 'search#reindex_specialist_sector_editions', as: 'reindex_specialist_sector_editions'
        end

        get 'find-in-admin-bookmarklet' => 'find_in_admin_bookmarklet#index', as: :find_in_admin_bookmarklet_instructions_index
        get 'find-in-admin-bookmarklet/:browser' => 'find_in_admin_bookmarklet#show', as: :find_in_admin_bookmarklet_instructions

        resources :users, only: [:index, :show, :edit, :update]

        resources :authors, only: [:show]
        resource :document_searches, only: [:show]
        resources :document_collections, path: "collections", except: [:index] do
          resources :document_collection_groups, as: :groups, path: 'groups' do
            member { get :delete }
            resource :document_collection_group_membership, as: :members,
                                                        path: 'members',
                                                        only: [:destroy]
          end
          resource :document_collection_group_membership, as: :new_member,
                                                      path: 'members',
                                                      only: [:create]
          post 'groups/update_memberships' => 'document_collection_groups#update_memberships', as: :update_group_memberships
        end
        resources :organisations do
          resources :groups, except: [:show]
          resources :corporate_information_pages do
            resources :translations, controller: 'corporate_information_pages_translations'
          end
          resources :contacts do
            resources :translations, controller: 'contact_translations', only: [:create, :edit, :update, :destroy]
            member do
              post :remove_from_home_page
              post :add_to_home_page
            end
            post :reorder_for_home_page, on: :collection
          end
          resources :social_media_accounts
          resources :translations, controller: 'organisation_translations'
          resources :promotional_features do
            resources :promotional_feature_items, as: :items, path: 'items', except: [:index]
          end
          member do
            get :features, localised: true
            get :people
          end
          resource :featured_topics_and_policies_list, path: 'featured-topics-and-policies', only: [:show, :update]
          resources :financial_reports, except: [:show]
          resources :offsite_links
        end

app/models/feature_list.rb
class FeatureList < ActiveRecord::Base
  has_many :features, dependent: :destroy, order: :ordering, before_add: :ensure_ordering!
  belongs_to :featurable, polymorphic: true

  validates_presence_of :locale
  validates_uniqueness_of :locale, scope: [:featurable_id, :featurable_type]

  accepts_nested_attributes_for :features

  def to_s
    "#{featurable.name} (#{locale})"
  end

  def reorder!(new_ordering)
    Feature.connection.transaction do
      start_at = next_ordering
      new_ordering.each.with_index do |feature_id, i|
        feature = self.features.find_by_id!(feature_id)
        feature.ordering = start_at + i
        feature.save!
      end
    end
    true
  rescue ActiveRecord::RecordNotFound => e
    self.errors[:base] << "Can't reorder because '#{e}'"
    false
  rescue ActiveRecord::RecordInvalid => e
    self.errors[:base] << "Can't reorder because '#{e}' on '#{e.record}'"
    false
  end

  def current
    features.current.includes([:topical_event, { document: :published_edition }])
  end

  def published_features
    features.current.with_published_edition
  end

  def topical_events
    features.current.with_topical_events
  end

  def empty?
    current.empty?
  end

private
  def next_ordering
    (features.map(&:ordering).max || 0) + 1
  end

  def ensure_ordering!(new_feature)
    new_feature.ordering = next_ordering unless new_feature.ordering
  end
end

app/controllers/admin/feature_lists_controller.rb
class Admin::FeatureListsController < Admin::BaseController
  before_filter :find_feature_list

  def show
    redirect_to feature_list_path(@feature_list)
  end

  def reorder
    new_order = (params[:ordering] || []).sort_by { |k, v| v.to_i }.map(&:first)
    if @feature_list.reorder!(new_order)
      message = {notice: "Feature order updated"}
    else
      message = {alert: "Unable to reorder features because #{@feature_list.errors.full_messages.to_sentence}"}
    end
    redirect_to feature_list_path(@feature_list), message
  end

private
  def find_feature_list
    @feature_list = FeatureList.find(params[:id] || params[:feature_list_id])
  end

  def feature_list_path(feature_list)
    polymorphic_url([:features, :admin, feature_list.featurable], locale: feature_list.locale)
  end
end

app/views/admin/feature_lists/_current_feature_list.html.erb
<h2>Currently featured</h2>
<p class="warning">
  Warning: changes to features appear instantly on the live site.
</p>

<% if feature_list.features.current.any? %>
  <% if feature_list.features.current.many? %>
    <p>
      To change the order of your featured documents, drag them up or down and then click "Save ordering".
    </p>
  <% end %>
  <%= form_for feature_list, url: reorder_admin_feature_list_path(feature_list), method: :post do |form| %>
    <fieldset class="sortable">
      <% @feature_list.features.current.each do |feature| %>
        <div class="well feature-list">
          <%= label_tag "ordering-#{feature.id}" do %>
            <div class="icon"><i class="icon-align-justify"></i></div>
            <% if feature.document && feature.document.published_edition %>
              <div class="title"><%= link_to(feature, admin_edition_path(feature.document.published_edition)) %></div>
              <div class="type"><%= feature.document.published_edition.type.titleize %> (document)</div>
              <div class="date"><%=localize feature.document.published_edition.major_change_published_at.to_date %></div>
              <%= content_tag_for :div, feature.document.published_edition, class: "button" do %>
                <%= link_to('Unfeature', unfeature_admin_feature_list_feature_path(feature_list, feature), confirm: "Unfeature '#{feature}'?", method: :post, class: "btn btn-danger") %>
              <% end %>
            <% elsif feature.topical_event %>
              <div class="title"><%= link_to feature.topical_event, edit_admin_topical_event_path(feature.topical_event) %></div>
              <div class="type">Topical Event</div>
              <div class="date"><%= l feature.topical_event.start_date.to_date %> to <%= l feature.topical_event.end_date.to_date %></div>
              <%= content_tag_for :div, feature.topical_event, class: "button" do %>
                <%= link_to('Unfeature', unfeature_admin_feature_list_feature_path(feature_list, feature), confirm: "Unfeature '#{feature}'?", method: :post, class: "btn btn-danger") %>
              <% end %>
            <% elsif feature.offsite_link %>
              <div class="title"><%= link_to feature.offsite_link, polymorphic_path([:edit, :admin, feature.offsite_link.parent, feature.offsite_link]) %></div>
              <div class="type"><%= feature.offsite_link.humanized_link_type %> (offsite link)</div>
              <div class="date"><%=localize feature.offsite_link.date.to_date if feature.offsite_link.date %></div>
              <%= content_tag_for :div, feature.offsite_link, class: "button" do %>
                <%= link_to('Unfeature', unfeature_admin_feature_list_feature_path(feature_list, feature), confirm: "Unfeature '#{feature}'?", method: :post, class: "btn btn-danger") %>
              <% end %>
            <% else %>
              <%= feature.document ? feature.document.latest_edition : "No edition" %>
            <% end %>
          <% end %>
          <%= text_field_tag "ordering[#{feature.id}]", feature.ordering, id: "ordering-#{feature.id}", class: "ordering" %>
        </div>
      <% end %>
    </fieldset>
    <%= form.submit "Save ordering", class: "btn btn-primary btn-large" %>
  <% end %>
<% else %>
  <p>Nothing featured yet</p>
<% end %>

app/views/admin/feature_lists/_featurable_editions.html.erb
<% if featurable_editions.present? %>
  <table class="table table-striped">
    <thead>
      <tr class="table-header">
        <th>Type</th>
        <th>Title</th>
        <th>Published</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% featurable_editions.each do |edition| %>
        <% edition = LocalisedModel.new(edition, feature_list.locale) %>
        <% next if feature_list.features.current.detect {|f| f.document == edition.document } %>
        <%= content_tag_for :tr, edition do %>
          <td class="type"><%= edition.type.titleize %></td>
          <td><%= link_to edition.title, admin_edition_path(edition) %></td>
          <td><%=localize edition.major_change_published_at.to_date %></td>
          <td>
            <%= link_to("Feature", polymorphic_url([:new, :admin, @feature_list, :feature], edition_id: edition), class: 'btn') %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate featurable_editions, theme: 'twitter-bootstrap' %>
<% else %>
  <div class="no-content no-content-bordered">
    No documents found
  </div>
<% end %>

app/views/admin/feature_lists/_featurable_offsite_links.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% featurable_offsite_links.each do |offsite_link| %>
    <% next if feature_list.features.current.detect {|f| f.offsite_link == offsite_link } %>
    <%= content_tag_for :tr, offsite_link do %>
      <td><%= link_to offsite_link.title, polymorphic_path([:edit, :admin, offsite_link.parent, offsite_link]) %></td>
      <td><%= offsite_link.humanized_link_type %></td>
      <td>
        <%= link_to("Feature", polymorphic_url([:new, :admin, @feature_list, :feature], offsite_link_id: offsite_link.id), class: 'btn') %>
      </td>
      <td>
        <%= button_to("Delete", polymorphic_url([:admin, offsite_link.parent, offsite_link]),
            method: :delete,
            class: "btn btn-danger",
            confirm: "Are you sure you want to delete this offsite link?")
         %>
      </td>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/admin/feature_lists/_featurable_topical_events.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Duration</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% featurable_topical_events.each do |event| %>
      <% next if feature_list.features.current.detect {|f| f.topical_event == event } %>
      <%= content_tag_for :tr, event do %>
        <td><%= link_to event.name, admin_topical_event_path(event) %></td>
        <td><%= l event.start_date.to_date %> to <%= l event.end_date.to_date %></td>
        <td>
          <%= link_to("Feature", polymorphic_url([:new, :admin, @feature_list, :feature], topical_event_id: event.id), class: 'btn') %>
        </td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/feature_lists/_feature_list.html.erb
<%= render partial: 'admin/feature_lists/current_feature_list', locals: {feature_list: feature_list} %>

<hr />
<h2 class="add-bottom-margin feature-title">Feature new documents</h2>
<div class="row-fluid">
  <div class="span3">
    <%= render partial: 'admin/editions/filter_options', locals: { filter_by: filter_by, filter_action: polymorphic_url([:features, :admin, feature_list.featurable], locale: feature_list.locale) } %>
  </div>
  <div class="span9" id="search_results">
    <%= render partial: "admin/feature_lists/search_results", locals: {feature_list: feature_list} %>
  </div>
</div>

<div class="feature-column">
  <% if @featurable_topical_events.any? %>
    <h2 class="feature-title">Feature new topical events</h2>
    <div class="row-fluid">
      <%= render partial: 'admin/feature_lists/featurable_topical_events', locals: { feature_list: feature_list, featurable_topical_events: @featurable_topical_events } %>
    </div>
  <% end %>
</div>

<div class="feature-column">
  <h2 class="feature-title">Feature new offsite link</h2>
  <% if @featurable_offsite_links.any? %>
    <div class="row-fluid">
      <%= render partial: 'admin/feature_lists/featurable_offsite_links', locals: { feature_list: feature_list, featurable_offsite_links: @featurable_offsite_links } %>
    </div>
  <% else %>
    <p>There are currently no offsite links.</p>
  <% end %>
</div>

app/views/admin/feature_lists/_search_results.html.erb
<h3 class="add-bottom-margin">
  <%= @filter.page_title %>
</h3>

<%= render partial: 'admin/feature_lists/featurable_editions', locals: { feature_list: feature_list, featurable_editions: @filter.editions(feature_list.locale) } %>