config/routes.rb
class AdminRequest
  def self.matches?(request)
    !invalid_admin_host?(request.host)
  end

  def self.invalid_admin_host?(host)
    Rails.env.production? && Whitehall.admin_host != host
  end
end

Whitehall::Application.routes.draw do
  def redirect(path, options = {prefix: Whitehall.router_prefix})
    super(options[:prefix] + path)
  end

  def external_redirect(path_prefix, target)
    get path_prefix => redirect(target, prefix: '')
    get "#{path_prefix}/*anything" => redirect(target, prefix: '')
  end

  root to: redirect("/admin/"), constraints: lambda { |request|
    ::Whitehall.admin_host == request.host
  }

  get '/government/ministers/minister-of-state--11' => redirect('/government/people/kris-hopkins', prefix: '')

  get '/browse/*parent_tag/:id', to: 'mainstream_categories#show'

  namespace 'api' do
    resources :detailed_guides, path: 'specialist', only: [:show, :index], defaults: { format: :json } do
      collection do
        get :tags
      end
    end
    resources :organisations, only: [:index, :show], defaults: { format: :json }
    resources :world_locations, path: 'world-locations', only: [:index, :show], defaults: { format: :json } do
      resources :worldwide_organisations, path: 'organisations', only: [:index], defaults: { format: :json }
    end
    resources :worldwide_organisations, path: 'worldwide-organisations', only: [:show], defaults: { format: :json }
  end

  scope Whitehall.router_prefix, shallow_path: Whitehall.router_prefix do
    external_redirect '/organisations/ministry-of-defence-police-and-guarding-agency',
      "http://webarchive.nationalarchives.gov.uk/20121212174735/http://www.mod.uk/DefenceInternet/AboutDefence/WhatWeDo/SecurityandIntelligence/MDPGA/"

    root to: redirect("/", { prefix: '' }), via: :get, as: :main_root
    get "/how-government-works" => "home#how_government_works", as: 'how_government_works'
    scope '/get-involved' do
      root to: 'home#get_involved', as: :get_involved, via: :get
      get 'take-part' => redirect('/get-involved#take-part')
      get 'take-part/:id', to: 'take_part_pages#show', as: 'take_part_page'
    end

    # Past foreign secretaries are currently hard-coded, so this
    # resource falls straight through to views.
    resources :past_foreign_secretaries, path: "/history/past-foreign-secretaries", only: [:index, :show]
    # Past chancellors is also hard-coded
    get "history/past-chancellors" => 'historic_appointments#past_chancellors'

    # Past foreign secretaries and past chancellors are here for the
    # purposes of reversing URLs in a consistent way from other views.

    # TODO: make these dynamic, they're hard-coded above.
    get "/history/:role" => "historic_appointments#index", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: 'historic_appointments'
    get "/history/:role/:person_id" => "historic_appointments#show", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: 'historic_appointment'
    resources :histories, path: "history", only: [:index, :show]

    resource :email_signups, path: 'email-signup', only: [:create, :new]
    get "/email-signup", to: redirect('/')

    get '/feed' => 'home#feed', defaults: { format: :atom }, constraints: { format: :atom }, as: :atom_feed
    get '/tour' => redirect("/tour", prefix: "")

    resources :announcements, only: [:index], path: 'announcements', localised: true
    resources :policies, only: [:index, :show], localised: true do
      member do
        get :activity
      end
      resources :supporting_pages, path: "supporting-pages", only: [:index, :show]
    end
    resources :news_articles, path: 'news', only: [:show], localised: true
    resources :fatality_notices, path: 'fatalities', only: [:show]
    get "/news" => redirect("/announcements"), as: 'news_articles'
    get "/fatalities" => redirect("/announcements"), as: 'fatality_notices'

    get "/latest" => 'latest#index', as: 'latest'

    resources :publications, only: [:index, :show], localised: true
    get "/publications/:publication_id/:id" => 'html_attachments#show', as: 'publication_html_attachment'

    resources :case_studies, path: 'case-studies', only: [:show, :index], localised: true
    resources :speeches, only: [:show], localised: true
    resources :statistical_data_sets, path: 'statistical-data-sets', only: [:index, :show]
    get "/speeches" => redirect("/announcements")
    resources :statistics_announcements, path: 'statistics/announcements', only: [:index, :show]
    resources :statistics, only: [:index, :show], localised: true
    resources :world_location_news_articles, path: 'world-location-news', only: [:index, :show], localised: true

    resources :worldwide_priorities, path: "priority", only: [:index, :show], localised: true do
      member do
        get :activity
      end
    end

    resources :consultations, only: [:index, :show] do
      collection do
        get :open
        get :closed
        get :upcoming
      end
    end
    get "/consultations/:consultation_id/:id" => 'html_attachments#show', as: 'consultation_html_attachment'

    resources :topics, path: "topics", only: [:index, :show]
    resources :topical_events, path: "topical-events", only: [:index, :show] do
      resource :about_pages, path: "about", only: [:show]
    end

    resources :document_collections, only: [:show], path: 'collections'
    get '/collections' => redirect("/publications")
    resources :organisations, only: [:index], localised: false
    resources :organisations, only: [:show], localised: true do
      get '/series/:slug' => redirect("/collections/%{slug}")
      get '/series' => redirect("/publications")

      member do
        get :consultations
        get :chiefs_of_staff, path: 'chiefs-of-staff'
      end
      resources :corporate_information_pages, only: [:show, :index], path: 'about', localised: true
      resources :groups, only: [:show]
    end
    get "/organisations/:organisation_id/groups" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/services-information" => 'services_and_information#show',
      as: :services_and_information
    get "/organisations/:organisation_slug/email-signup" => 'email_signup_information#show',
      as: :organisation_email_signup_information

    resources :ministerial_roles, path: 'ministers', only: [:index, :show], localised: true
    resources :people, only: [:index, :show], localised: true

    resources :policy_groups, path: 'groups', only: [:index, :show]
    resources :operational_fields, path: 'fields-of-operation', only: [:index, :show]
    resources :worldwide_organisations, path: 'world/organisations', only: [:show, :index], localised: true do
      resources :corporate_information_pages, only: [:show], path: 'about', localised: true
      resources :worldwide_offices, path: 'office', only: [:show]
    end

    resources :embassies, path: 'world/embassies', only: [:index]

    resources :world_locations, path: 'world', only: [:index, :show], localised: true
    get 'world/organisations/:organisation_id/office' => redirect('/world/organisations/%{organisation_id}')
    get 'world/organisations/:organisation_id/about' => redirect('/world/organisations/%{organisation_id}')

    constraints(AdminRequest) do
      namespace :admin do
        root to: 'dashboard#index', via: :get

        namespace :api do
          post 'reindex-specialist-sector-editions/*slug', to: 'search#reindex_specialist_sector_editions', as: 'reindex_specialist_sector_editions'
        end

        get 'find-in-admin-bookmarklet' => 'find_in_admin_bookmarklet#index', as: :find_in_admin_bookmarklet_instructions_index
        get 'find-in-admin-bookmarklet/:browser' => 'find_in_admin_bookmarklet#show', as: :find_in_admin_bookmarklet_instructions

        resources :users, only: [:index, :show, :edit, :update]

        resources :authors, only: [:show]
        resource :document_searches, only: [:show]
        resources :document_collections, path: "collections", except: [:index] do
          resources :document_collection_groups, as: :groups, path: 'groups' do
            member { get :delete }
            resource :document_collection_group_membership, as: :members,
                                                        path: 'members',
                                                        only: [:destroy]
          end
          resource :document_collection_group_membership, as: :new_member,
                                                      path: 'members',
                                                      only: [:create]
          post 'groups/update_memberships' => 'document_collection_groups#update_memberships', as: :update_group_memberships
        end
        resources :organisations do
          resources :groups, except: [:show]
          resources :corporate_information_pages do
            resources :translations, controller: 'corporate_information_pages_translations'
          end
          resources :contacts do
            resources :translations, controller: 'contact_translations', only: [:create, :edit, :update, :destroy]
            member do
              post :remove_from_home_page
              post :add_to_home_page
            end
            post :reorder_for_home_page, on: :collection
          end
          resources :social_media_accounts
          resources :translations, controller: 'organisation_translations'
          resources :promotional_features do
            resources :promotional_feature_items, as: :items, path: 'items', except: [:index]
          end
          member do
            get :features, localised: true
            get :people
          end
          resource :featured_topics_and_policies_list, path: 'featured-topics-and-policies', only: [:show, :update]
          resources :financial_reports, except: [:show]
          resources :offsite_links
        end

app/controllers/home_controller.rb
class HomeController < PublicFacingController
  layout 'frontend'

  enable_request_formats feed: [:atom]

  def feed
    @recently_updated = Edition.published.in_reverse_chronological_order.includes(:document).limit(10)
  end

  def how_government_works
    sitewide_setting = load_reshuffle_setting
    @is_during_reshuffle = sitewide_setting.on if sitewide_setting
    @policy_count = Policy.published.count
    sorter = MinisterSorter.new
    @cabinet_minister_count = sorter.cabinet_ministers.count - 1 # subtract one to discount PM
    @other_minister_count = sorter.other_ministers.count
    @all_ministers_count = @cabinet_minister_count + @other_minister_count + 1 # add one to put the PM back in
    @ministerial_department_count = Organisation.listable.ministerial_departments.count
    @non_ministerial_department_count = Organisation.listable.non_ministerial_departments.count
  end

  def get_involved
    @open_consultation_count = Consultation.published.open.count
    @closed_consultation_count = Consultation.published.closed_since(1.year.ago).count
    @next_closing_consultations = decorate_collection(Consultation.published.open.order("closing_at asc").limit(1), PublicationesquePresenter)
    @recently_opened_consultations = decorate_collection(Consultation.published.open.order("opening_at desc").limit(3), PublicationesquePresenter)
    @recent_consultation_outcomes = decorate_collection(Consultation.published.closed.responded.order("closing_at desc").limit(3), PublicationesquePresenter)
    @take_part_pages = TakePartPage.in_order
  end

  def history_king_charles_street
  end

  def history_lancaster_house
  end
end

app/views/home/get_involved.html.erb
<% page_title "Get involved" %>
<% page_class "get-involved" %>


<header class="block headings-block">
  <div class="inner-block floated-children">
    <%= render partial: 'shared/heading',
              locals: { big: true,
                        heading: "Get involved" } %>
    <p class="intro-paragraph">Find out how you can <a href="#engage-with-government">engage with government</a> directly, and <a href="#take-part">take&nbsp;part</a> locally, nationally or internationally. You can also <a href="#related-polices">read&nbsp;policies</a> about how government is increasing participation.</p>
  </div>
</header>

<div class="block">
  <div class="inner-block floated-children">
    <h2 id="engage-with-government">Engage with government</h2>
    <section class="respond-to-consultations">
      <div class="head-section">
        <h3>Respond to consultations</h3>
      </div>
      <div class="column">
        <div class="content">
          <p>You can give your views on new or changing government policies by responding to consultations. Government departments take these responses into consideration before making decisions.</p>
        </div>
      </div>
    </section>
    <section class="consultations">
      <div class="head-section">
        <dl class="values">
          <dt><%= link_to @open_consultation_count, publications_filter_path(:publication_filter_option => 'open-consultations') %>
        </dt>
          <dd>Open consultations</dd>
          <dt><%=  link_to @closed_consultation_count, publications_filter_path(:publication_filter_option => 'closed-consultations') %></dt>
          <dd>Closed consultations in the past 12 months</dd>
          <% if false # this count not implemented yet %>
            <dt><a href="#">29</a></dt>
            <dd>Responses in the past 12 months</dd>
          <% end %>
        </dl>
      </div>
      <div class="consultation-lists">
        <div class="consultation-closing-soon">
          <% @next_closing_consultations.each do |consultation| %>
            <h3><%= consultation.time_until_closure %></h3>
          <% end %>
          <ol class="document-list">
            <% @next_closing_consultations.each do |consultation| %>
              <%= content_tag_for(:li, consultation, class: 'document-row') do %>
                <h3><%= consultation.title %></h3>
                <ul class="attributes">
                  <li><%= link_to "Read and respond", public_document_path(consultation) %></li>
                </ul>
              <% end %>
            <% end %>
          </ol>
        </div>
        <div>
          <div class="column">
            <div class="content">
              <h3>Recently opened</h3>
              <ol class="document-list">
                <% @recently_opened_consultations.each do |consultation| %>
                  <li class="document-row">
                    <h3><%= link_to consultation.title, public_document_path(consultation) %></h3>
                    <ul class="attributes">
                      <li><%= consultation.organisations.map(&:acronym).to_sentence %></li>
                      <li>Closes <%= consultation.date_microformat(:closing_at) %></li>
                      <li><%= link_to "Read and respond", public_document_path(consultation) %></li>
                    </ul>
                  </li>
                <% end %>
              </ol>
              <p class="see-all"><%= link_to("Search all consultations", publications_path(publication_filter_option: "consultations")) %></p>
            </div>
          </div>
          <div class="column">
            <div class="content">
              <h3>Recent outcomes</h3>
              <ol class="document-list">
                <% @recent_consultation_outcomes.each do |consultation| %>
                  <li class="document-row">
                    <h3><%= link_to consultation.title, public_document_path(consultation) %></h3>
                    <ul class="attributes">
                      <li><%= consultation.organisations.map(&:acronym).to_sentence %></li>
                      <li>Closed <%= consultation.date_microformat(:closing_at) %></li>
                      <li><%= link_to "See the outcome", public_document_path(consultation) %></li>
                    </ul>
                  </li>
                <% end %>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </section>
    <hr class="keyline">
    <section class="start-a-petition">
      <div class="head-section">
        <h3>Start a petition</h3>
      </div>
      <div class="column">
        <div class="content">
          <p>You can <a href="http://epetitions.direct.gov.uk/" rel="external">create an e&ndash;petition</a> to influence government and Parliament. If the petition gets at least 100,000 online signatures, it will be considered for debate in the House of Commons.</p>
        </div>
      </div>
    </section>
    <hr class="keyline">
    <section class="comment-follow">
      <div class="head-section">
        <h3>Follow a blog or social media channel</h3>
      </div>
      <div class="column">
        <div class="content">
          <p>For an instant way to interact with government departments, try their social media streams. These are listed under 'Follow us' on the department's home page. As well as access to blogs, audio, video and more, you can comment, debate and rate.</p>
          <p class="see-all"><a href="/government/organisations/">See all government departments</a></p>
          <p>Some active government blogs include:</p>
          <ul class="index-list">
            <li><a href="https://history.blog.gov.uk" rel="external">History of Government</a></li>
            <li><a href="https://quarterly.blog.gov.uk" rel="external">Civil Service Quarterly</a></li>
            <li><a href="http://blogs.dfid.gov.uk" rel="external">DfID bloggers</a></li>
            <li><a href="http://blogs.fco.gov.uk" rel="external">FCO bloggers</a></li>
            <li><a href="http://digital.cabinetoffice.gov.uk" rel="external">Goverment Digital Service</a></li>
            <li><a href="http://www.civilservice.gov.uk/about/hocs/blog" rel="external">Head of the Civil Service</a></li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</div>


<div class="block">
  <div class="inner-block floated-children featured-news">
    <h2 id="take-part">Take part</h2>
    <section class="take-part-pages">
      <%= render @take_part_pages %>
    </section>
    <hr class="keyline">
    <section class="more-ways">
      <div class="head-section">
        <h3>More ways to take part</h3>
      </div>
      <div class="column">
        <div class="content">
          <p>Many people are already volunteering, donating and contributing, both in the UK and abroad. If you&rsquo;d like to join them, but don&rsquo;t know where to start, here&rsquo;s a list of suggestions:</p>
          <ul class="index-list">
            <li><a href="http://www.volunteerics.org/" rel="external">Join the International Citizen Service (18- to 25-year-olds)</a></li>
            <li><a href="http://www.ourwatch.org.uk/get_involved/" rel="external">Take part in your local Neighbourhood Watch</a></li>
            <li><a href="http://www.bigsocietyawards.org/" rel="external">Nominate someone for a Big Society Award</a></li>
            <li><a href="/donating-to-charity">Make a donation to charity</a></li>
            <li><a href="http://schoolsonline.britishcouncil.org/programmes-and-funding/linking-programmes-worldwide/connecting-classrooms" rel="external">Link up with a school overseas </a></li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</div>

<div class="block">
  <div class="inner-block floated-children">
    <section class="policies">
      <h2 id="related-polices">Related policies</h2>
      <div class="head-section">
        <div class="content">
          <p>The government wants to make it easier for people to be involved in decision&ndash;making. To find out what this means for you, take a look at the policies featured here:</p>
        </div>
      </div>
      <div class="column">
        <div class="content">
          <ol class="document-list">
            <li class="document-row">
              <h3><a href="/government/policies/making-it-easier-to-set-up-and-run-a-charity-social-enterprise-or-voluntary-organisation">Making it easier to set up and run a charity, social enterprise, or voluntary organisation</a></h3>
              <ul class="attributes">
                <li>Cabinet Office</li>
                <li>Community and society</li>
              </ul>
            </li>
            <li class="document-row">
              <h3><a href="/government/policies/improving-the-transparency-and-accountability-of-government-and-its-services">Improving the transparency and accountability of government and its services</a></h3>
              <ul class="attributes">
                <li>Cabinet Office and Efficiency and Reform Group</li>
                <li>Government efficiency, transparency and accountability</li>
              </ul>
            </li>
            <li class="document-row">
              <h3><a href="/government/policies/increasing-the-number-of-academies-and-free-schools-to-create-a-better-and-more-diverse-school-system">Increasing the number of academies and free schools to create a better and more diverse school system</a></h3>
              <ul class="attributes">
                <li>Department for Education</li>
                <li>Schools</li>
              </ul>
            </li>
            <li class="document-row">
              <h3><a href="/government/policies/promoting-social-action-encouraging-and-enabling-people-to-play-a-more-active-part-in-society/supporting-pages/national-citizen-service">Promoting social action: encouraging and enabling people to play a more active part in society</a></h3>
              <ul class="attributes">
                <li>Cabinet Office</li>
                <li>Community and society</li>
              </ul>
            </li>
            <li class="document-row">
              <h3><a href="/government/policies/transforming-government-services-to-make-them-more-efficient-and-effective-for-users/supporting-pages/increasing-the-quality-of-public-services-with-commercial-models-and-public-service-mutuals">Transforming government services to make them more efficient and effective for users</a></h3>
              <ul class="attributes">
                <li>Cabinet Office and Efficiency and Reform Group</li>
                <li>Government efficiency, transparency and accountability</li>
              </ul>
            </li>
            <li class="document-row">
              <h3><a href="/government/policies/giving-people-more-power-over-what-happens-in-their-neighbourhood">Giving people more power over what happens in their neighbourhood</a></h3>
              <ul class="attributes">
                <li>DCLG</li>
                <li>Community and society</li>
              </ul>
            </li>
            <li class="document-row">
              <h3><a href="/government/policies/giving-communities-more-power-in-planning-local-development">Giving communities more power in planning local development</a></h3>
              <ul class="attributes">
                <li>DCLG</li>
                <li>Planning and building</li>
              </ul>
            </li>
            <li class="document-row">
              <h3><a href="/government/policies/promoting-social-action-encouraging-and-enabling-people-to-play-a-more-active-part-in-society">Promoting social action: encouraging and enabling people to play a more active part in society</a></h3>
              <ul class="attributes">
                <li>CO</li>
                <li>Community and society</li>
              </ul>
            </li>
          </ol>
        </div>
      </div>
    </section>
  </div>
</div>